config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'
  get 'home/index'
  root to: "home#index"
  


  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }
  resource :users

  resources :images do
    resources :comments
    member do
      put 'like' => 'images#like'
      
    end
  end
  get '*path' => redirect('/')
  default_url_options :host => "localhost:3000"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    can :read, :all # permissions for every user, even if not logged in    
    if user.present?  # additional permissions for logged in users (they can manage their posts)
      can :manage, Image, user_id: user.id 
      can :like, Image
      if user.permission_level == 1  # additional permissions for administrators
        can :manage, :all
      end
    end

   
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
    #after_create :send_new_post_email
    mount_uploader :picture, PictureUploader
    validates :description, presence: true 
    belongs_to :user
    has_many :comments, dependent: :destroy
    acts_as_votable

    private
    def send_new_post_email
    ImageMailer.image_notification(self).deliver
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#,
         #:confirmable
  has_many :images
  acts_as_voter

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_params, if: :devise_controller?
    #before_action :authenticate_user!, except: [:index, :show]
    
    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_path, alert:"No tienes Permisos, intenta iniciar sesión"
    end
    
    protected
    def configure_devise_params
        devise_parameter_sanitizer.permit(:sign_up) do |user|
            user.permit(:name, :email, :password, :password_confirmation)
        end
    end
    
    def authenticate_user!
        if user_signed_in?
            super
        else
            redirect_to new_user_session_path if request.original_fullpath != new_user_session_path
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @image = Image.find(params[:image_id])
          @comment = @image.comments.create(params[:comment].permit(:name, :comment))
        redirect_to image_path(@image)    
    end
  
    def destroy
        @image = Image.find(params[:image_id])
        @comment = @image.comments.find(params[:id])
        @comment.destroy
        redirect_to image_path(@image)
    end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

    private
      def after_confirmation_path_for(resource_name, resource)
        sign_in(resource)
        images_path
      end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
    def saludo
        @myName = "Diego"
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @all_images = Image.paginate(page: params[:page], per_page: 9).order(id: :desc).all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    respond_to :js, :html, :json
    load_and_authorize_resource param_method: :image_params

    before_action :set_image, only: [:show, :edit, :update, :destroy]
    
    

    def index
        if user_signed_in?
        @images = Image.order(id: :desc).where user_id: current_user.id
        end
        
        @all_images = Image.order(id: :desc).all
    end
    
    def new 
        @image = Image.new   
    end

    def create
        @image = current_user.images.new image_params
        if @image.save
            return redirect_to @image
        else
            render :new
        end
        
      
    end

    def show

    end

    def edit
    end

    def update
        @image.update image_params
        redirect_to images_path
    end

    def destroy
        @image.destroy
        redirect_to images_path(@image)
    end

    def like
        if current_user.voted_for? @image
            @image.unliked_by current_user
        else
            @image.liked_by current_user
        end
        redirect_to image_path(@image)
    end  
    def set_image
        @image = Image.find params[:id]
    end
    
    private
    def image_params
        params.require(:image).permit :description, :picture
    end



    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    respond_to :js, :html, :json
    load_and_authorize_resource param_method: :user_params
    before_action :set_user, only: [:show, :edit, :update] # probably want to keep using this
    
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
  
    # # GET /users/1
    # # GET /users/1.json
    def show
  
    end

    def create
    
    end
  
    # GET /users/1/edit
    def edit
  
    end
  
    # # PATCH/PUT /users/1
    # # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      private
      def user_params
        params.require(:user).permit(:role, :user_name)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/_comment.html.erb
<div class="be-comment-block mt-4">
	<div class="be-comment">
		<div class="be-img-comment">	
			<a>
				<img src="https://www.computerhope.com/jargon/g/guest-user.jpg" alt="" class="be-ava-comment">
			</a>
		</div>
		<div class="be-comment-content">
			<span class="be-comment-name">
				<a style="color: white;"><%= comment.name %></a>
			</span>
			<span class="be-comment-time">
				<i class="fa fa-clock-o"></i>
				<%= comment.created_at %>
			</span>
			<p class="be-comment-text">
				<%= comment.comment %>
			</p>
            <!--<%= link_to 'Delete', [comment.image, comment],
                  method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>-->
		</div>
	</div>
</div>

app/views/comments/_form.html.erb
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->

<div class="form-group" style="margin: 5%">
    <%= simple_form_for([@image, @image.comments.build]) do |f| %>
        <%= f.label :nombre, class: 'h5 text-light' %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :comentario, class: 'h5 mt-4 text-light' %>
        <%= f.text_area :comment, class: 'form-control'%>
        <br>
        <%= f.button :submit, 'Ok', class: "btn btn-dark mt-4" %>
    <% end %>
</div>

app/views/control/saludo.html.erb
<p>saludo desde acá <%= @myName %> </p>

app/views/home/index.html.erb
    
<div class="row ml-4">
    <%- @all_images.each do |image|  %>
    <div class="col-md-4 ">
        <div class="card mt-4" style="width: 90%">
            <%= image_tag image.picture.thumb.url, class: 'card-img-top'%>
            <div class="card-body">
            
                <p class="card-text"><%= image.description%></p>
                <%= link_to t('.info_link'), image, class: 'btn btn-info' %>
            </div>
           
        </div>
    </div>
    <% end %>
    <div class="apple_pagination">
    <%= will_paginate @all_images %>
    </div>
    
</div>
    

app/views/home/index.js.erb
$("#all_images").html("<%= escape_javascript(render("all_images")) %>");

app/views/images/_form.html.erb
<div class="form-group" style="margin: 5%">
    <p class="h3">Sube tu Post</p>
    <%= form_for @image, builder: CustomFormBuilder do |f| %>
        
        <%= f.form_error %>
        
        <%= f.label :description, class: 'h5 text-white' %>
        <%= f.text_field :description, class: 'form-control' %>
        <%= f.field_error :description %>
        <br>
        <%= f.label :picture, class: 'h5 mt-4 text-white' %>
        <%= f.file_field :picture, class: 'text-white'%>
        <br>
        
        <%= f.submit 'Enviar', class: 'btn btn-dark mt-4' %>
    <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-4">
    <div class="card mt-4" style="width: 90%;">
        <%= image_tag image.picture.thumb.url, class: 'card-img-top'%>
        <div class="card-body">
            <p class="card-text"><%= image.description%></p>
            <%= link_to t('.edit_link'), edit_image_path(image), class: 'btn btn-primary' %>
            <%= link_to t('.delete_link'), image, method: :delete, data: { confirm: 'sure?'}, class: 'btn btn-danger' %>
            <%= link_to t('.info_link'), image, class: 'btn btn-info' %>
        </div>
    </div>
</div>

app/views/images/_like_link.html.erb
<% vote_text = current_user&.voted_for?(image) ? "No me gusta" : "Me gusta" %>

<%= link_to vote_text, like_image_path(image), method: :put, remote: :true, class: 'like-post' %>

app/views/images/_likes.html.erb
<%= image.get_upvotes.size %>

app/views/images/edit.html.erb
<p class="h3">Editar Imagen</p>
<%= render 'form' %>

app/views/images/index.html.erb
<div>
    <img src="assets/default.jpg" style="width: 20%" class="rounded float-left ml-5" alt="...">
    <ul class="nav" style="margin-left: 35%">
        <li>
        <p> <%= @current_user.name %> </p>
        </li>
    </ul>
    <ul class="nav" style="margin-left: 35%">
        <%- if @images.count != 0%>
        <li>
            <p><strong><%= @images.count %> Publicaciones</strong></p>
        </li>
        <% else %>
        <li>
            <p><strong>Tienes 0 Publicaciones</strong></p>
            <a href="/images/new">Crea tu primera publicacion! </a>
        </li>
        <% end %>
    </ul>
<div>

<div class="row mt-5 ml-2">
    <%- if @current_user.permission_level == 1 %>
        <%- @all_images.each do |image|  %>
        <div class="col-4">
            <div class="card mt-4" style="width: 90%;">
                <%= image_tag image.picture.thumb.url, class: 'card-img-top'%>
                <div class="card-body">
                    <p class="card-text"><%= image.description%></p>
                    <%= link_to t('.edit_link'), edit_image_path(image), class: 'btn btn-primary' %>
                    <%= link_to t('.delete_link'), image, method: :delete, data: { confirm: 'sure?'}, class: 'btn btn-danger' %>
                    <%= link_to t('.info_link'), image, class: 'btn btn-info' %>
                </div>
            </div>
        </div>
        <% end %>
    <% else %>
        <%- @images.each do |image|  %>
        <div class="col-4">
            <div class="card mt-4" style="width: 90%;">
                <%= image_tag image.picture.thumb.url, class: 'card-img-top'%>
                <div class="card-body">
                    <p class="card-text"><%= image.description%></p>
                    <%= link_to t('.edit_link'), edit_image_path(image), class: 'btn btn-primary' %>
                    <%= link_to t('.delete_link'), image, method: :delete, data: { confirm: 'sure?'}, class: 'btn btn-danger' %>
                    <%= link_to t('.info_link'), image, class: 'btn btn-info' %>
                </div>
            </div>
        </div>
        <% end %>
    <% end %>
    
</div>
    

app/views/images/like.js.erb
$("#like-count").html("<%= j render 'images/likes', image: @image %>");
$("#like-link").html("<%= j render 'images/like_link', image: @image %>");

app/views/images/new.html.erb
<%= render 'form'%>

app/views/images/show.html.erb
<div class="card mx-auto " style="width: 50%;">
    <%= image_tag @image.picture.medium.url, class: 'card-img-top' %>
    <div class="card-body">
        <p class="card-text"><%= @image.description %></p><hr class="bg-light">
        <h5 class='pt-2'>
            <div id="like-count text-light">
                <%= render 'images/likes', image: @image %><i class="fa fa-heart pl-2"></i>
            </div>
             <div id="like-link">
                <%= render 'images/like_link', image: @image %>
            </div>
            <hr>
        </h5>
  </div>
</div>
<section class="section comments pt-4">
    <div class="container">
        <h4 class="subtitle is-5"><strong><%= @image.comments.count %></strong> Comentario(s)</h4>
        <%= render @image.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Deja un comentario</h3>
            <%= render 'comments/form' %>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="container mt-4">
        
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/">INSTA-RAILS </a>
      
        <ul class="nav justify-content-end">

          <%- if user_signed_in?%>
            <a class="nav-link disabled text-info" href="#">Bienvenido <%= current_user.name  %> </a>
            <li class="nav-item">
              <%= link_to 'Nuevo Post', new_image_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Mi Perfil', images_path , method: :get, class: 'nav-link' %>
            </li>
            <li class="nav-item pt-2">
              <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            
            
          <% else %>
            <li class="nav-item">
              <%= link_to 'Iniciar Sesión', new_user_session_path , class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Registrarse', new_user_registration_path , class: 'nav-link' %>
            </li>
          <% end %>

        </ul>
       
      </nav>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <%= yield %>  
    </div>
    
  </body>
</html>